<?php

function security_advisories_menu()
{
  $items['admin/reports/vulnerabilities'] = [
    'title' => 'Vulnerabilities',
    'description' => "List of all vulnerable modules and core vulnerabilities.",
    'page callback' => 'advisories_view',
    'access callback' => TRUE
  ];

  $items['admin/reports/vulnerabilities/list'] = [
    'title' => 'List',
    'description' => "List of all vulnerable modules and core vulnerabilities.",
    'page callback' => 'advisories_view',
    'access callback' => TRUE
  ];

  $items['admin/reports/vulnerabilities/notifier'] = [
    'title' => 'Notify',
    'description' => "Send an e-mail to the defined relevant parties.",
    'page callback' => 'advisories_notify',
    'access callback' => TRUE
  ];

  $items['admin/config/system/vulnerabilities'] = [
    'title' => 'Set Notification Recipients',
    'description' => "Set the relevant parties to be informed when sending out notifications.",
    'page callback' => 'advisories_notify',
    'access callback' => TRUE
  ];

  return $items;
}

function advisories_view()
{
  $items = [
    'table'   => \Drupal\security_advisories\Renderer::infoTable()
  ];
  
  return $items;
}

function advisories_notify()
{
  $items = [];

  $notifier = new \Drupal\security_advisories\Notifier();
  $notifier->send();

  return $items;
}